== Introduction

=== Basic Formattings

//tag::01[]
[.target]
Some basic formattings are *bold* and _italics_.
//end::01[]

=== Sentences and Paragraphs

//tag::04[]
[.target]
--
Two sentences across several lines.
They are all displayed as one paragraph.
--
//end::04[]

//tag::05[]
[.target]
--
Two sentences displayed as two paragraphs.

The additional space between them shows visually that they are distinct.
--
//end::05[]

//tag::06[]
[.target]
--
Sometimes you don't want a new paragraph +
but just a new line. +
The space between these two lines is just if there was an automatic break within a paragraph.
--
//end::06[]

//tag::07[]
[.target]
As a developer, chance are that you want to format some words with a `mono-spaced` font to show that this is code.
//end::07[]

//tag::08[]
[.target]
```
10 print "Hello World"
20 goto 10
```
//end::08[]

//tag::09[]
[.target]
[source, groovy]
----
10.times {
    println "Hello World"
}
----
//end::09[]

//tag::10[]
[.target]
[source, groovy, linenums]
----
10.times {
    println "Hello World"
}
----
//end::10[]

=== Strike through

//tag::02[]
[.target]
Some advanced formatting is [.line-through]#strike through#.
//end::02[]

//tag::03[]
[.target]
And you can even #highlight# some text.
//end::03[]

