ifndef::imagesdir[:imagesdir: ../images]

//Recap

=== Attribute

Attribute sind Variablen, die mit `:name: wert` definiert werden und mit `\{name}` referenziert werden.

https://docs.asciidoctor.org/asciidoc/latest/attributes/document-attributes/[📖, role=docs, target=docs]

'''
//solution
:projekt: AsciiDocKoans
:version: 2.0

Willkommen bei {projekt} Version {version}.

'''
//hint
`:name: wert` zum Definieren, `\{name}` zum Verwenden.

'''
Willkommen bei AsciiDocKoans Version 2.0.

''''

Attribute eignen sich auch zum Setzen von Dokumenteigenschaften wie Autor und Datum.

'''
//solution
:author: Ralf D. Müller
:revdate: 2026-04-06

Dieses Dokument wurde von {author} am {revdate} erstellt.

'''
//hint
`:author:` und `:revdate:` sind vordefinierte AsciiDoc-Attribute.

'''
Dieses Dokument wurde von Ralf D. Müller am 2026-04-06 erstellt.

''''

Mit dem Attribut `:toc:` lässt sich ein Inhaltsverzeichnis erzeugen.

'''
//solution
:toc:

= Mein Dokument

== Erstes Kapitel

== Zweites Kapitel

'''
//hint
`:toc:` am Anfang des Dokuments. Die Überschriften bilden automatisch das Inhaltsverzeichnis.

'''
= Mein Dokument

== Erstes Kapitel

== Zweites Kapitel

''''

Attribute können auch als Schalter dienen: gesetzt oder nicht gesetzt.

'''
//solution
:experimental:

Drücke kbd:[Ctrl+S] zum Speichern.

'''
//hint
`:experimental:` aktiviert UI-Macros wie `kbd:[]` für Tastenkombinationen.

'''
Drücke Ctrl+S zum Speichern.

