ifndef::imagesdir[:imagesdir: ../images]

//Recap

=== Überschriften

Überschriften werden je nach Tiefe mit einem oder mehreren `=` gefolgt von einem Leerzeichen markiert.

Die Überschrift mit nur _einem_ `=` entspricht dabei dem Titel des Dokuments und darf dementsprechend nur einmal vorkommen.

Teildokumente sollten immer mit der Überschriften-Tiefe `==` beginnen.

https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#section-titles[📖, role=docs, target=docs]

'''
//solution
= Document Title (Level 0)

== Level 1 Section Title

== Level 1 Section Title

=== Level 2 Section Title

==== Level 3 Section Title

'''
//hint
`=` für Level 0, `==` für Level 1, `===` für Level 2 usw. Leerzeichen nach den Gleichheitszeichen nicht vergessen.

'''
// Deine Eingabe
Document Title (Level 0)

Level 1 Section Title

Level 1 Section Title

Level 2 Section Title

Level 3 Section Title


// next task

''''

AsciiDoc beherrscht automatische Nummerierung der Überschriften.

'''
//solution
:numbered:

= Document Title (Level 0)

== Level 1 Section Title

== Level 1 Section Title

=== Level 2 Section Title

==== Level 3 Section Title

'''
//hint
Das Attribut `:numbered:` am Anfang des Dokuments aktiviert die automatische Nummerierung.

'''
= Document Title (Level 0)

== Level 1 Section Title

== Level 1 Section Title

=== Level 2 Section Title

==== Level 3 Section Title

''''

Jede Überschrift kann automatisch verlinkt werden.

'''
//solution
:sectanchors:

= Document Title (Level 0)

== Level 1 Section Title

== Level 1 Section Title

=== Level 2 Section Title

==== Level 3 Section Title

'''
//hint
Das Attribut `:sectanchors:` fügt Anker-Links zu jeder Überschrift hinzu.

'''
= Document Title (Level 0)

== Level 1 Section Title

== Level 1 Section Title

=== Level 2 Section Title

==== Level 3 Section Title


