ifndef::imagesdir[:imagesdir: ../images]

//Recap

=== Sourcecode

Code-Blöcke werden mit vier Bindestrichen `----` eingegrenzt.

https://docs.asciidoctor.org/asciidoc/latest/verbatim/source-blocks/[📖, role=docs, target=docs]

'''
//solution
----
10 print "Hello World"
20 goto 10
----

'''
//hint
Vier Bindestriche vor und nach dem Code.

'''
10 print "Hello World"
20 goto 10

''''

Syntax-Highlighting wird über ein `[source]`-Attribut mit Sprachname aktiviert.

'''
//solution
[source, groovy]
----
println "Hello World"
if (true) {
    println "AsciiDoc is great"
}
----

'''
//hint
`[source, groovy]` vor den Bindestrichen.

'''
println "Hello World"
if (true) {
    println "AsciiDoc is great"
}

''''

Callouts markieren wichtige Stellen im Code mit nummerierten Referenzen.

https://docs.asciidoctor.org/asciidoc/latest/verbatim/callouts/[📖, role=docs, target=docs]

'''
//solution
[source, groovy]
----
println "Hello World" // <1>
if (true) {
    println "AsciiDoc is great" // <2>
}
----
<1> Ausgabe auf der Konsole
<2> Bedingte Ausgabe

'''
//hint
`// <1>` im Code, `<1> Erklärung` darunter.

'''
[source, groovy]
----
println "Hello World"
if (true) {
    println "AsciiDoc is great"
}
----
Ausgabe auf der Konsole
Bedingte Ausgabe

''''

Auch ohne `[source]` kann man einfache Literalblöcke erstellen. Vier Punkte `....` erzeugen einen Literal-Block ohne Syntax-Highlighting.

'''
//solution
....
Dies ist ein Literal-Block.
  Einrückungen bleiben erhalten.
    Kein Syntax-Highlighting.
....

'''
//hint
Vier Punkte `....` statt vier Bindestriche.

'''
Dies ist ein Literal-Block.
  Einrückungen bleiben erhalten.
    Kein Syntax-Highlighting.

