ifndef::imagesdir[:imagesdir: ../images]

//Recap

=== Attribute und Dokumenteigenschaften

Attribute steuern das Verhalten von AsciiDoc-Dokumenten.

https://docs.asciidoctor.org/asciidoc/latest/attributes/document-attributes/[📖, role=docs, target=docs]

Mit dem Attribut `:toc:` wird ein Inhaltsverzeichnis erzeugt.

'''
//solution
:toc:

= Mein Dokument

== Erstes Kapitel

== Zweites Kapitel

'''
//hint
`:toc:` am Anfang des Dokuments. Die Überschriften bilden automatisch das Inhaltsverzeichnis.

'''
= Mein Dokument

== Erstes Kapitel

== Zweites Kapitel

''''

Das Attribut `:experimental:` aktiviert UI-Macros wie `kbd:[]` für Tastenkombinationen.

'''
//solution
:experimental:

Drücke kbd:[Ctrl+S] zum Speichern.

'''
//hint
`:experimental:` am Anfang, dann `kbd:[Tasten]` im Text.

'''
Drücke Ctrl+S zum Speichern.

''''

Mit `:numbered:` werden Überschriften automatisch nummeriert.

'''
//solution
:numbered:

= Projekthandbuch

== Einleitung

== Architektur

=== Bausteinsicht

'''
//hint
`:numbered:` am Anfang des Dokuments.

'''
= Projekthandbuch

== Einleitung

== Architektur

=== Bausteinsicht

''''

Mit `:sectanchors:` bekommt jede Überschrift einen klickbaren Anker-Link.

'''
//solution
:sectanchors:

= Projekthandbuch

== Einleitung

== Architektur

'''
//hint
`:sectanchors:` am Anfang des Dokuments.

'''
= Projekthandbuch

== Einleitung

== Architektur

