:experimental:
:toc: left
:toc:

++++
<style>
div.target {
    border: 1px solid #888888;
    padding: 10px;
    border-radius: 5px;
    margin-bottom: 10px;
}
div.target:before {
    content: 'target';
    font-family: arial, sans-serif;
    background-color: white;
    position: relative;
    top: -18px;
    padding: 3px 6px;
    width: 30px;
}
div.input {
    border: 2px solid #888888;
    padding: 10px;
    border-radius: 5px;
    margin-bottom: 10px;
}
div.input:before {
    content: 'your result';
    font-family: arial, sans-serif;
    background-color: white;
    position: relative;
    top: -18px;
    padding: 3px 6px;
    width: 30px;
}
</style>
<script>
// when changing this script, the HTML preview in the IntelliJ AsciiDoc plugin will not refresh its contents
// until you close and re-open the editor OR disable the option "refresh preview contents without flicker"

function check() {
    var targets = document.getElementsByClassName('target');

    var getNextSibling = function (elem, selector) {

        // Get the next sibling element
        var sibling = elem.nextElementSibling;

        // If the sibling matches our selector, use it
        // If not, jump to the next sibling and continue the loop
        while (sibling) {
            if (sibling.matches(selector)) return sibling;
            sibling = sibling.nextElementSibling
        }

    };

    [].forEach.call(targets, function (target) {

        var targetHTML = target.innerHTML.replace(/data-line-[^ "]+/,'');
        var input = getNextSibling(target, '.input');
        var inputHTML = input.innerHTML.replace(/data-line-[^ "]+/,'');
        //useful for debugging
        //document.write('<textarea style="width: 100%; height:100%">'+inputHTML+"\n"+targetHTML);
        if (targetHTML === inputHTML) {
            input.style.borderColor = '#88ff88';
        } else {
            input.style.borderColor = '#ff8888';
        }
    });
}

document.addEventListener("DOMContentLoaded", function() {
    check();

    var oldProcessLinks = __IntelliJTools && __IntelliJTools.processLinks;
    // if this is in the preview window in the IDE, run the checks
    if (oldProcessLinks) {
        __IntelliJTools.processLinks = function() {
            oldProcessLinks();
            check();
        }
    }
});

</script>

++++